[tool.black]
line-length = 148

[tool.poetry]
name = "tappr"
version = "0.21.0"
description = "CLI for Tanzu Application Platform"
authors = ["Atman Dhol <github.com/atmandhol>"]

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.9.0"
click = "8.1.2"
python-jose = ">=3.0.0"
requests = ">=2.0.0"
netaddr = "^0.8.0"
urllib3 = "^1.26.6"
pyfiglet = "^0.8.post1"
xmltodict = "^0.12.0"
kubernetes = ">=26.0.0"
rich = ">=0.0.0"
colorama = "^0.4.4"
typing-extensions = "^4.2.0"
typer-cli = ">=0.0.0"
windows-curses = {version = "^2.2.0", platform = "win32"}
prompt-toolkit = "^3.0.29"
black = "21.4b0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
tappr = "tappr.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
